# Generated by Django 4.2.4 on 2023-08-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0002_alter_platformtoken_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtoken',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
