# Generated by Django 4.2.4 on 2023-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssParamsTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('platform_name', models.CharField(max_length=256)),
                ('protocol', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('tags', models.CharField(max_length=1024)),
                ('additional_params', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=1024)),
                ('running_cycle', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RSS采集模板',
                'verbose_name_plural': 'RSS采集模板',
                'db_table': 'rss_template',
                'ordering': ['id'],
            },
        ),
    ]
