# Generated by Django 4.2.4 on 2023-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssparamstemplate',
            name='route',
            field=models.CharField(default='/', max_length=1024),
            preserve_default=False,
        ),
    ]
