# Generated by Django 4.2.4 on 2023-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_management', '0003_rssparamstemplate_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssparamstemplate',
            name='category',
            field=models.CharField(default='未分类', max_length=256),
        ),
    ]
