# Generated by Django 4.2.4 on 2023-11-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_management', '0004_alter_rssparamstemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssparamstemplate',
            name='deploy_status',
            field=models.CharField(default='未部署', max_length=256),
        ),
    ]
